"""Create initial tables

Revision ID: 5c2490ea9afc
Revises: 
Create Date: 2025-09-07 13:18:50.790114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2490ea9afc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_index('idx_dedup_file_hash', 'dedup_index', ['file_hash'], unique=False)
    op.create_index('idx_dedup_url_hash', 'dedup_index', ['url_hash'], unique=False)
    op.create_index(op.f('ix_dedup_index_case_id'), 'dedup_index', ['case_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_idempotency_keys_case_id'), 'idempotency_keys', ['case_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('VICTIM', 'OFFICER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submitter_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_normalized', sa.Text(), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'ESCALATED', 'MATCH_FOUND', 'COMPLETED', name='casestate'), nullable=False),
    sa.Column('assigned_officer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('due_by', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_case_assigned', 'cases', ['assigned_officer_id', 'state'], unique=False)
    op.create_index('idx_case_file_hash', 'cases', ['file_hash'], unique=False)
    op.create_index('idx_case_state_due', 'cases', ['state', 'due_by'], unique=False)
    op.create_index('idx_case_url_hash', 'cases', ['url_hash'], unique=False)
    op.create_index(op.f('ix_cases_assigned_officer_id'), 'cases', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_due_by'), 'cases', ['due_by'], unique=False)
    op.create_index(op.f('ix_cases_file_hash'), 'cases', ['file_hash'], unique=False)
    op.create_index(op.f('ix_cases_state'), 'cases', ['state'], unique=False)
    op.create_index(op.f('ix_cases_url_hash'), 'cases', ['url_hash'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_action'), 'case_events', ['action'], unique=False)
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_events_created_at'), 'case_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_events_created_at'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_action'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_cases_url_hash'), table_name='cases')
    op.drop_index(op.f('ix_cases_state'), table_name='cases')
    op.drop_index(op.f('ix_cases_file_hash'), table_name='cases')
    op.drop_index(op.f('ix_cases_due_by'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_officer_id'), table_name='cases')
    op.drop_index('idx_case_url_hash', table_name='cases')
    op.drop_index('idx_case_state_due', table_name='cases')
    op.drop_index('idx_case_file_hash', table_name='cases')
    op.drop_index('idx_case_assigned', table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_idempotency_keys_case_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_dedup_index_case_id'), table_name='dedup_index')
    op.drop_index('idx_dedup_url_hash', table_name='dedup_index')
    op.drop_index('idx_dedup_file_hash', table_name='dedup_index')
    op.drop_table('dedup_index')
    # ### end Alembic commands ###
